### ISSUE TITLE
Install script SODIUM_CRYPTO_SECRETBOX_KEYBYTES missing/password complexity

### ISSUE THREAD

**Issue by egreenspan2** [CiscoSE/iPSK-Manager#1]
Install.php fails because SODIUM_CRYPTO_SECRETBOX_KEYBYTES is not defined under Centos 8.1.1911 with PHP 7.2.11

Similar to this [post](https://github.com/jedisct1/libsodium-php/issues/172)

In addition:
With mysql secure installation the function to generate random password randomly can generate password not meeting the complexity criteria, resulting in failure to create mysql user.

Default complexity rules for MySql 8 are:
mysql> SHOW VARIABLES LIKE 'validate_password%';

+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password.check_user_name    | ON     |
| validate_password.dictionary_file    |        |
| validate_password.length             | 8      |
| validate_password.mixed_case_count   | 1      |
| validate_password.number_count       | 1      |
| validate_password.policy             | MEDIUM |
| validate_password.special_char_count | 1      |
+--------------------------------------+--------+

A very bad hack is to simply append mixed case, number and special char to the random password, but clearly that is not very secure.

OS: CentOS 8.1.1911
Mysql: 8.0.17

**Comment by cisco-garyoppel** [comment]
Thank you for opening this issue, the password complexity issue has been resolved.

The Installer has been updated to include several updates that include:
- Rolling back failed installation allowing the process to be run again
- Increased password length for the manager and ISE DB User accounts to 20

Closing with Commit f7f5b7e0db8179586b3bbbd29797610099787c38

If you have further issues, please re-open or open a new issue.
