### ISSUE TITLE
accountEnabled | Attribute | OBDC Connection

### ISSUE THREAD

**Issue by sdh91** [CiscoSE/iPSK-Manager#10]
accountEnabled is not an attribute that can be pulled via the OBDC connection when connecting to ISE. This would be helpful to be able to validated an account is suspended or not. 

Currently a suspended account and expired account can still connect.

**Comment by cisco-garyoppel** [comment]
Thank you for opening this issue, this has now been resolved and will be closed.

The 'accountExpired' attribute is updated within the stored procedure with every DB call that is made by ISE.  

Please review the DB_CHANGELOG @ [https://github.com/CiscoSE/iPSK-Manager/blob/master/DB_CHANGELOG.md](https://github.com/CiscoSE/iPSK-Manager/blob/master/DB_CHANGELOG.md)

Further details on this issue found can be found at issue #11 which has been closed with Commit f7f5b7e0db8179586b3bbbd29797610099787c38
