### ISSUE TITLE
MySql 8 installation GRANT fails

### ISSUE THREAD

**Issue by egreenspan2** [CiscoSE/iPSK-Manager#2]
In installer.inc.php the GRANT to mysql.proc fails as that table has been finally retired.

$iseSqlPermissions[3] = "GRANT SELECT ON `mysql`.`proc` TO '{$_SESSION['iseusername']}'@'%'";

What are the thoughts on removing that line as the stored proc permissions should be granted by SELECT permission on the database.

**Comment by uck9** [comment]
May be best to actually note that the MySQL version requirement should be 5.7 and not to run with v8.  When trying to integrate the MySQL db with ISE and running the connection test while having Stored Procedures configured always shows the SP's as not existing.

Logging the queries on the mysql server shows the following query run as part of the connection test:

select name from mysql.proc where name='iPSK_FetchGroups' and db='ipsk' LIMIT 0, 25

Would appear that this reference to mysql.proc is hard coded in ISE (2.6 at least).  I'd say just easier to stick with ver 5.7 for MySQL at this point.

**Comment by egreenspan2** [comment]
Understood, thank you for the feedback
