### ISSUE TITLE
Ubuntu 20 Failing Installation

### ISSUE THREAD

**Issue by sdh91** [CiscoSE/iPSK-Manager#6]
During installation on Ubuntu 20 the blow error is seen during the initial installation wizard. 

![ipsk-manger-failure](https://user-images.githubusercontent.com/38229736/90153731-566b7e80-dd57-11ea-9116-dd9163b62d00.JPG)

I assumed this was an error on my part the first time or two. After the third or fourth time, I realized that it wasn't me. I attempted to completed on Ubuntu 18 and the same steps worked without niche.

 - OS: Ubuntu 20
 - Browser: Firefox
 - Version

**Comment by cisco-garyoppel** [comment]
Thank you for opening this issue, this has now been resolved and will be closed.

The Installer has been updated to include several updates that include:
- Rolling back failed installation allowing the process to be run again
- Increased password length for the manager and ISE DB User accounts to 20

Closed with Commit f7f5b7e0db8179586b3bbbd29797610099787c38
